import './globals.css'
import { Dosis } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import ReduxProvider from '@/redux/reduxProvider/ReduxProvider';
import AuthProviders from '@/providers/authProviders/AuthProviders';


const dosis = Dosis({
  weight: ['400', '500', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'SyncroBiz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
      </head>
      <body className={dosis.className}>
        <ReduxProvider>
          <AuthProviders>
            {children}
            <Toaster></Toaster>
          </AuthProviders>
        </ReduxProvider>
      </body>
    </html>
  )
}
