import AuthProviders from '@/providers/authProviders/authProviders';
import './globals.css'
import { Dosis } from 'next/font/google';

const dosis = Dosis({
  weight: ['400', '500', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'SyncroBiz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
      </head>
      <body className={dosis.className}><AuthProviders>{children}</AuthProviders>
      </body>
    </html>
  )
}
